server:
  port: 9001

spring:
  application:
    name: userService

  datasource:

    url: jdbc:mariadb://localhost:3306/BBS
    username: root
    password: 5466
    driver-class-name: org.mariadb.jdbc.Driver

#    url: jdbc:mariadb://192.168.0.4:3306/co_option
#    username: hammer
#    password: hammer
#    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:mapper/*.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cooption.userservice.vo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
